import { Suspense, StrictMode } from 'react'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import ReduxProvider from './components/ReduxProvider'
import { HashConnectClient } from './components/HashButton'
import { ThemeProvider } from './theme'
import { CssBaseline } from '@mui/material'
import { store } from './store'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <HashConnectClient />
          <ThemeProvider>
            <CssBaseline />
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
        </ReduxProvider>

      </body>
    </html>
  )
}


