import { Suspense } from 'react'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={null}>
          <Navbar />
          {children}
          <Footer /></Suspense>
      </body>
    </html>
  )
}
